// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Layout(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"es-AR\"><head><meta charset=\"utf-8\"><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/layout.templ`, Line: 8, Col: 17}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><meta name=\"viewport\" content=\"width=device-width\"><link rel=\"stylesheet\" href=\"estilos/styles.css\"><!-- <link rel=\"icon\" sizes=\"16x16 32x32 48x48\" type=\"image/png\" href=\"\"/> --><!-- <link rel=\"alternate\" href=\"https://www.machinelearningworkshop.com/fr/\" hreflang=\"fr-FR\" /> --><!-- <link rel=\"canonical\" href=\"base sin traduccion\" /> --><script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js\" integrity=\"sha384-/TgkGk7p307TH7EXJDuUlgG3Ce1UVolAOFopFekQkkXihi5u/6OCvVKyz1W+idaz\" crossorigin=\"anonymous\" defer>\n    </script><meta name=\"htmx-config\" content='{\n        \"responseHandling\": [\n        { \"code\": \"200\", \"swap\": \"true\" },\n        { \"code\": \"422\", \"swap\": \"true\" },\n        { \"code\": \"500\", \"swap\": \"true\" }\n        ]\n    }'></head><body><a class=\"skip-link\" href=\"#contenido\">Ir al contenido principal</a><header><nav role=\"menu\"><a href=\"/\" role=\"menuitem\">Inicio</a> <a href=\"/proyectos\" role=\"menuitem\">Proyectos</a> <a href=\"/contacto\" role=\"menuitem\">Contacto</a></nav></header><main id=\"contenido\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</main><footer><p>© 2026</p><div><p>Contacto: </p><address><a href=\"https://www.linkedin.com/in/edmundo-agust%C3%ADn-r%C3%BAveda/\" target=\"_blank\"><img href=\"\" alt=\"enlace a linkedin del autor: Edmundo Agustin Ruveda.\"> Linkedin</a> <a href=\"https://github.com/Agustin-del\" target=\"_blank\"><img href=\"\" alt=\"enlace a github del autor: Edmundo Agustin Ruveda.\"> Github</a></address></div></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
